blueprint:
  name: "Adaptive Lighting Compesation (Sigmoide & Soft Transit)"
  description: >
    Adjusts brightness with a sigmoid curve and handles ON/OFF.
    Returns control to AL at sunset smoothly.
  domain: automation
  input:
    illuminance_sensor:
      name: External lux sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    adaptive_lighting_switch:
      name: Switch Adaptive Lighting
      selector:
        entity:
          domain: switch
    light_target:
      name: Light controlled by Adaptive Lighting
      selector:
        entity:
          domain: light
    lux_midpoint:
      name: Inflection point (Lux)
      default: 2500
      selector:
        number:
          min: 100
          max: 10000
          unit_of_measurement: lx
    br_max:
      name: Max brightness
      description: Percentage of brightness when it's dark outside (Default 100%).
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    br_min:
      name: Minimum brightness. (During the day)
      default: 10
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: "%"
    steepness:
      name: Curve steepness (K)
      description: Determines how "quick" the transition is. 0.002 (default) is a balanced value.
      default: 0.002
      selector:
        number:
          min: 0.0001
          max: 0.01
          step: 0.0001
    sun_elevation_limit:
      name: Sun elevation threshold (Soft Transit)
      description: Raise it to make the transition at sunset smoother.
      default: 2.0
      selector:
        number:
          min: -2
          max: 10
          step: 0.5
          unit_of_measurement: "°"
    auto_turn_on:
      name: "Enable auto turn-on"
      default: false
      selector:
        boolean:

mode: restart

variables:
  input_sensor: !input illuminance_sensor
  al_switch: !input adaptive_lighting_switch
  l_mid: !input lux_midpoint
  b_max: !input br_max
  b_min_val: !input br_min
  k_val: !input steepness
  sun_limit: !input sun_elevation_limit
  auto_on: !input auto_turn_on
  light_entity: !input light_target

trigger:
  - platform: state
    entity_id: !input illuminance_sensor
  - platform: state
    entity_id: sun.sun

action:
  - variables:
      lux: "{{ states(input_sensor) | float(0) }}"
      elevation: "{{ state_attr('sun.sun', 'elevation') | float(0) }}"

  - choose:
      # During the day: The sun is above the transition threshold
      - conditions:
          - condition: template
            value_template: "{{ elevation > sun_limit }}"
        sequence:
          - service: adaptive_lighting.change_switch_settings
            data:
              entity_id: !input adaptive_lighting_switch
              use_defaults: current
              max_brightness: >
                {% set e = 2.71828 %}
                {% set exponent = k_val * (lux - l_mid) %}
                {% set denom = 1 + (e ** exponent) %}
                {% set sigmoide = b_min_val + (b_max - b_min_val) / denom %}
                {{ [[sigmoide, b_max]|min, b_min_val]|max | round(0) }}
          
          - if:
              - condition: template
                value_template: "{{ auto_on and is_state(light_entity, 'off') and lux < l_mid }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input light_target

      # SUNSET/NIGHT: The sun is setting, return the control to Adaptive-Lighting
      - conditions:
          - condition: template
            value_template: "{{ elevation <= sun_limit }}"
        sequence:
          - service: adaptive_lighting.change_switch_settings
            data:
              entity_id: !input adaptive_lighting_switch
              use_defaults: "configuration"
